### PR TITLE
Add a fallback to multicast

### PR DESCRIPTION
**Pull request by blink1073**
Implements Multicast support, and uses a default Multicast port when there is no suitable interface present.  

I tested this on OS X using `chat.py` with and without an internet connection.

### CODE REVIEW

**Comment by sphaero** [comment]
Can you change the multicast address to 225.25.25.25 
You're using a reserved address: http://www.iana.org/assignments/multicast-addresses/multicast-addresses.xhtml
225.25.25.25 was the one used before.

**Comment by blink1073** [comment]
Done!

**Comment by sphaero** [comment]
225, it's 224 now :)

**Comment by blink1073** [comment]
Updated, and tested again on OS X.

**Comment by sphaero** [comment]
Thanks! If you want you can also make a PR for the AUTHORS file

**Pull request merged**
