### PR TITLE
Measure and Improve Test Coverage

### PR DESCRIPTION
**Pull request by blink1073**
Adds coveralls support for Pyre, and improves coverage by 5%.

Before:

```
---------- coverage: platform darwin, python 3.4.3-final-0 -----------
Name                 Stmts   Miss  Cover
----------------------------------------
pyre/__init__            2      0   100%
pyre/pyre              149     53    64%
pyre/pyre_group         23      4    83%
pyre/pyre_node         337     43    87%
pyre/pyre_peer         101     14    86%
pyre/zactor             76     14    82%
pyre/zbeacon           187     44    76%
pyre/zhelper           250    130    48%
pyre/zre_msg           281     65    77%
pyre/zsocket            16      1    94%
setup                    5      5     0%
tests/test_pyre        110      7    94%
tests/test_zactor       27     10    63%
tests/test_zbeacon      59     16    73%
tests/test_zhelper      20      1    95%
----------------------------------------
TOTAL                 1643    407    75%
----------------------------------------------------------------------
Ran 16 tests in 11.301s
```

After:

```
---------- coverage: platform darwin, python 3.4.3-final-0 -----------
Name                 Stmts   Miss Branch BrMiss  Cover
------------------------------------------------------
pyre/__init__            2      0      0      0   100%
pyre/pyre              110     10      8      4    88%
pyre/pyre_group         18      0      4      0   100%
pyre/pyre_node         337     39    130     32    85%
pyre/pyre_peer         101     14     12      6    82%
pyre/zactor             74     13      8      2    82%
pyre/zbeacon           174     32     70     18    80%
pyre/zhelper           250    111     78     38    55%
pyre/zre_msg           269     53     72     26    77%
pyre/zsocket            16      1      4      1    90%
tests/test_pyre        141      0      2      1    99%
tests/test_zactor       16      0      0      0   100%
tests/test_zbeacon      41      0      0      0   100%
tests/test_zhelper      25      0      6      0   100%
------------------------------------------------------
TOTAL                 1574    273    394    128    80%
----------------------------------------------------------------------
Ran 21 tests in 15.352s
```

### CODE REVIEW

**Comment by blink1073** [comment]
@sphaero, you'd have to go to https://coveralls.io to set this up.  Assuming you a member of the `zeromq` organization, you'd have to go in and make your membership public on Github, and then enable the repo on coveralls.

**Comment by blink1073** [comment]
The two big coverage offenders are `get_win_ifaddrs` (not much can be done other than skipping it on Travis), and the unimplemented sections of `zre_msg`.

**Comment by sphaero** [comment]
I don't know this service. What does it do exactly. It seems to benchmark the code? But from your diffs I only see code cleanup which might only improve startup time?

**Comment by blink1073** [comment]
The intent is to show what parts of the code base are covered by tests (they have a nice UI for it), which automatically updates for each build.  They also provide a badge that shows the test coverage for the project, an indication of health.

**Comment by blink1073** [comment]
I can add the badge to the Readme file as part of this PR if you like.

**Comment by blink1073** [comment]
See for example my project https://github.com/blink1073/oct2py.

**Pull request closed without merging**
