### PR TITLE
Problem: peers_by_group not implemented

### LINKED ISSUE #102: Obtaining Peers in Group
Hello

Thanks for the Python Port - I'm using it in a University project at the moment.
I would like to obtain a list of the current peers which are members of a specific group.

Pyre provides `Pyre.peers()` which seems to be an implementation of Zyre `zyre_peers()` (see below or https://github.com/zeromq/zyre#toc3-188) and according to my tests provides all peers.

Is there an implementation of Zyre z`yre_peers_by_group()` (see below or https://github.com/zeromq/zyre#toc3-188) which returns only peers which belong to this group?

If this is not implemented, could anyone recommend a way of achieving this?

Grateful for any assistance.

```
//  *** Draft method, for development use, may change without warning ***
    //  Return zlist of current peer ids.
    //  Caller owns return value and must destroy it when done.
    ZYRE_EXPORT zlist_t *
        zyre_peers (zyre_t *self);

    //  *** Draft method, for development use, may change without warning ***
    //  Return zlist of current peers of this group.
    //  Caller owns return value and must destroy it when done.
    ZYRE_EXPORT zlist_t *
        zyre_peers_by_group (zyre_t *self, const char *name);
```

### PR DESCRIPTION
**Pull request by papr**
Solution: Implement such a method as suggested by
https://github.com/zeromq/pyre/issues/102#issuecomment-258093666

Fixes #102

### CODE REVIEW

**Comment by keent** [comment]
@papr Thanks

**Comment by papr** [comment]
Conflicts from previous conflicts are solved.

**Comment by keent** [comment]
@papr Can you resolve the conflicts please? There's are a few leftover tags from diff.

**Comment by keent** [comment]
@papr  Ah nice. Just saw that. Merging now :)

**Pull request merged**
