### PR TITLE
Gracefully handle issues during zbeacon socket preparations

### PR DESCRIPTION
**Pull request by papr**
Possible workaround for https://github.com/zeromq/pyre/issues/137

### CODE REVIEW

**Comment by papr** [comment]
@keent Could you please trigger a manual version bump via https://github.com/zeromq/pyre/actions/workflows/bump_version.yml ?

**Comment by keent** [comment]
@papr Bump version fails with : 

```
Run ad-m/github-push-action@master
Push to branch master
Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

```

**Comment by papr** [comment]
https://github.com/zeromq/pyre/actions/runs/1078679721 this run was triggered by closing the PR which fails because the external repo PRs do not have access to the github token. You need to do a manual dispatch of the action https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

**Comment by keent** [comment]
@papr OK Done. Why is it missing the "build the source" and "deploy to Pypi" steps? Thanks

**Comment by papr** [comment]
Mmh, https://github.com/zeromq/pyre/actions/workflows/deploy.yml should be automatically triggered by new tags. Maybe, the bump version commit needs to use the personal access token for auth? :-/

https://github.com/zeromq/pyre/actions/workflows/deploy.yml can be triggered, manually, too, though.

**Comment by papr** [comment]
@keent Could you please try triggering https://github.com/zeromq/pyre/actions/workflows/deploy.yml manually?

**Comment by keent** [comment]
image

@papr 
I'm not able to see where I can click manual deploy

**Comment by keent** [comment]
image

status @papr

**Comment by papr** [comment]
@keent Yeah, I think we have to say goodbye to the idea of fully automated deployment for now. You should now be able to manually trigger the deployment for 0.3.4. No need to bump the version to 0.3.5 IMO.
Screenshot 2021-08-24 at 14 37 55

**Comment by keent** [comment]
@papr Forgot to say. But this was done 
image

**Pull request merged**
