### PR TITLE
Usability Enhancements

### PR DESCRIPTION
**Pull request by blink1073**
- Allow pip to install dependencies
- Fix support for Python 2
- Allow for a drop and return of connectivity
- Clean up Travis script

### CODE REVIEW

**Comment by sphaero** [comment]
It fails on python 3.2 as it doesn't support u"..." syntax

 File "tests/test_zactor.py", line 4, in <module>
    from pyre import zactor
  File "/home/travis/build/zeromq/pyre/pyre/__init__.py", line 3, in <module>
    from .pyre import Pyre
  File "/home/travis/build/zeromq/pyre/pyre/pyre.py", line 10, in <module>
    from . import zbeacon
  File "/home/travis/build/zeromq/pyre/pyre/zbeacon.py", line 40
    MULTICAST_GRP = u'225.25.25.25'
                                  ^
SyntaxError: invalid syntax

**Comment by blink1073** [comment]
All set!

**Comment by AxelVoitier** [comment]
There seems to be references to ipaddress module in zhelpers.py as well.

**Comment by blink1073** [comment]
Better?

**Comment by AxelVoitier** [comment]
Yes!
Thanks :)

**Comment by sphaero** [comment]
Thanks for the cleanup but I think you were a bit too enthousiastic:
```
Successfully installed ipaddress-1.0.7 pyre-0.2 pyzmq-14.5.0

0.23s$ cd; nosetests pyre

----------------------------------------------------------------------

Ran 0 tests in 0.000s
```

**Comment by blink1073** [comment]
All set!

**Comment by blink1073** [comment]
Argh, or not, hold on.

**Comment by blink1073** [comment]
Okay, *now* its ready:

```
----------------------------------------------------------------------
Ran 16 tests in 11.274s
OK
The command "nosetests -v --exe" exited with 0.
Done. Your build exited with 0.
```

**Pull request merged**
